# Adapted from https://git.realestate.com.au/the-money/mercury/blob/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.4.1

LineLength:
  Max: 140

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/NumericPredicate:
  Exclude:
    - 'app/validators/*'
